package main

//
// a word-count application "plugin" for MapReduce.
//
// go build -buildmode=plugin wc.go
//

import "6.5840/mr"
import "unicode"
import "strings"
import "strconv"

// 这个文件是一个统计单词的 MapReduce 插件。
// 它包含两个函数：Map 和 Reduce。
// Map 函数将输入文本拆分为单词，并为每个单词生成一个键值对 (word, "1")。
// Reduce 函数接收每个单词及其对应的值列表，并返回该单词的总出现次数。

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.

// Map 函数的逻辑是：
// 1. 定义一个函数 ff，用于检测非字母字符，作为单词的分隔符。
// 2. 使用 strings.FieldsFunc 函数，根据 ff 函数将输入内容拆分为单词数组。
// 3. 遍历单词数组，为每个单词创建一个键值对 (word, "1")，并将其添加到结果切片中。
// 4. 返回包含所有键值对的切片。
func Map(filename string, contents string) []mr.KeyValue {
	// function to detect word separators.
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	words := strings.FieldsFunc(contents, ff)

	kva := []mr.KeyValue{}
	for _, w := range words {
		kv := mr.KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
// Reduce 函数的逻辑是：
// 1. 接收一个单词（key）和该单词对应的值列表（values）。
// 2. 计算 values 列表的长度，即该单词的出现次数。
// 3. 将出现次数转换为字符串并返回。
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	return strconv.Itoa(len(values))
}

// Map 的输入是文件名和文件内容，输出是一个键值对切片，表示每个单词及其出现一次。
// Reduce 的输入是一个单词和该单词的所有出现次数的列表，输出是该单词的总出现次数。
